# ===============================================================================================================
# k-means clustering with ASA24 data.
# Version 1
# Created on 01/06/2022 by Rie Sadohara
# ===============================================================================================================

# Set your working directory as to the main directory.
  Session --> Set working directory --> Choose directory.
  setwd("~/GitHub/DietR")

# Name your main directory for future use. 
  main_wd <- file.path(getwd())

# Load necessary packages.
  library(ggfortify)
  library(gridExtra)
  library(cluster)
  library(ggplot2)
  
# Set your ggplot2 theme.
  theme_set(theme_bw(base_size = 14))

# Import source code to run the analyses to follow.
  source("lib/specify_data_dir.R")
  source("lib/k-means.R")
  
# You can come back to the main directory by:
  setwd(main_wd) 
  
# ===============================================================================================================
# Import data from your data directory 
# ===============================================================================================================

# In this section, we are going to perform k-means analysis for each of Nutrient as is, Nutrient average, 
# Food categories as is, and Food categories average.
  
# Before proceeding, ensure to have four directories (folders) named as: 
#   kmeans_Nut_asis
#   kmeans_Nut_ave
#   kmeans_Cat_asis
#   kmeans_Cat_ave
#   
# K-means analysis results will be saved in this folder.  You can change those directory names, but 
# if you do so, you will need to modify the directory name, "res_dir_xxx_xxxx", to match your new directory name.

# Specify the directory where the data is.
  SpecifyDataDirectory(directory.name = "eg_data/VVKAJ/")
  
# ===============================================================================================================
# Nutrient data as is, processed for clustering analyses.
# ===============================================================================================================

# Load Nut_asis data.
  Tot_m_QCed_Nut_asis <- read.table(file="VVKAJ_Tot_m_QCed_Nut_asis_c_rv.txt", sep="\t", header=T)
  
# Scale your input file and name it as k-means_input.
  kmeans_input <- scale(Tot_m_QCed_Nut_asis)
  
# Ensure your input file has the correct number of rows and columns.
  dim(kmeans_input)
  
# Specify the directory (folder) to save the results.
  res_dir_nut_asis = "kmeans_Nut_asis"
  
# Specify the prefix of filenames to be saved. 
  res_prefix_nut_asis = "VVKAJ_Nut_asis"
  
# Run the elbow, silhouette, and gap methods to find an optimum K (number of clusters). 
# Do not alter the name of the input file: kmeans_input. This function below assumes that
# the input is named as "kmeans_input". 
# You can only run those three methods for K = 1 through (number of observations - 1). 
# The gap method output will be printed on the Console. The gap values are plotted in 
# xxx_gapmethod.pdf.
  ChooseK(out.dir= res_dir_nut_asis, out.prefix= res_prefix_nut_asis)

# This code will generate three output files all at once in the res_dir_xxx_xxxx:
#     
#   Output file postfix    |	File content
#   -------------------    | ---------------------------------------------------------------
#   _elbowmethod.pdf	     |	Shows total within???clusters sum of squares for each K.
#   _gapmethod.pdf	       |	Shows the Gap statistic (k) for each K, and if the factoextra package is used, the optimal K is marked by a dotted line.
#   _silhouettemethod.pdf	 |	Shows the Average silhouette width (~ goodness of fit) for each K, and if the factoextra package is used, the optimal K is marked by a dotted line.
  
# Look at the three figures generated by the ChooseK function above. The elbow and gap methods did not give a 
# distinct peak, but the silhouette method gave a peak at K=4. K=2,3,4,5 also have relatively high silhouette 
# width (~goodness of fit).
  
# With specific K values in mind, perform k-means analysis with one specified K. This will save 
# Dim1 x Dim2 plot as a .pdf file in your out.dir. Change the filename as necessary. 
  OneK(myK= 4, out.dir= res_dir_nut_asis, out.fn = "VVKAJ_Nut_asis_K4")
  oneKplot
  
# Or try multiple Ks and print the biplots in one panel. Likewise, This will save a Dim1 x Dim2 plot for 
# each of the chosen K as a .pdf file in your out.dir. Change the filename to be saved as a PDF as necessary. 
# This function uses the factoextra and gridExtra packages. 
  MultipleK(myKs = c(2,3,4,5), out.dir = res_dir_nut_asis, out.fn = "VVKAJ_Nut_asis_K2-5")
  
# ===============================================================================================================
# Nutrient data averaged across days, processed for clustering analyses.
# ===============================================================================================================
                                         
# Load Nut_ave data.
  Tot_m_QCed_Nut_ave <- read.table(file="VVKAJ_Tot_mean_m_QCed_Nut_ave_c_rv.txt", sep="\t", header=T)
  
# Scale your input file and name it as k-means_input.
  kmeans_input <- scale(Tot_m_QCed_Nut_ave)
  
# Ensure your input file has the correct number of rows and columns.
  dim(kmeans_input)
  
# Specify the directory (folder) to save the results.
  res_dir_nut_ave = "kmeans_Nut_ave" 
  
# Specify the prefix of filenames to be saved. 
  res_prefix_nut_ave = "VVKAJ_Nut_ave"
  
# Run elbow, silhouette, and gap methods to find an optimum K (number of clusters). 
  ChooseK(out.dir= res_dir_nut_ave, out.prefix= res_prefix_nut_ave)
  
# With specific K values in mind, perform k-means analysis with one specified K.
  OneK(myK= 5, out.dir= res_dir_nut_ave, out.fn = "VVKAJ_Nut_ave_K5")  
  oneKplot
  
# Try multiple Ks and print the biplots in one panel.
  MultipleK(myKs = c(2,3,4,5), out.dir = res_dir_nut_ave, out.fn = "VVKAJ_Nut_ave_K2-5")
  

# ===============================================================================================================
# Food categories data as is, processed for clustering analyses.
# ===============================================================================================================
  
# Load Cat_asis data.
  Tot_m_QCed_Cat_asis <- read.table(file="VVKAJ_Tot_m_QCed_Cat_asis_c_rv.txt", sep="\t", header=T)
  
# Scale your input file and name it as k-means_input.
  kmeans_input <- scale(Tot_m_QCed_Cat_asis)
  
# Ensure your input file has the correct number of rows and columns.
  dim(kmeans_input)
  
# Specify the directory (folder) to save the results.
  res_dir_cat_asis = "kmeans_Cat_asis" 
  
# Specify the prefix of filenames to be saved. 
  res_prefix_cat_asis = "VVKAJ_Cat_asis"
  
# Run elbow, silhouette, and gap methods to find an optimum K (number of clusters). 
  ChooseK(out.dir= res_dir_cat_asis, out.prefix= res_prefix_cat_asis)
  
# With specific K values in mind, perform k-means analysis with one specified K.
  OneK(myK=3, out.dir= res_dir_cat_asis, out.fn = "VVKAJ_Cat_asis_K3")
  oneKplot
  
# Try multiple Ks and print the biplots in one panel.
  MultipleK(myKs = c(3,4,5,6), out.dir = res_dir_cat_asis, out.fn = "VVKAJ_Cat_asis_K3-6")
  

# ===============================================================================================================
# Food categories data averaged across days, processed for clustering analyses.
# ===============================================================================================================
  
# Load Cat_ave data.
  Tot_m_QCed_Cat_ave <- read.table(file="VVKAJ_Tot_mean_m_QCed_Cat_ave_c_rv.txt", sep="\t", header=T)
  
# Scale your input file and name it as k-means_input.
  kmeans_input <- scale(Tot_m_QCed_Cat_ave)
  
# Ensure your input file has the correct number of rows and columns.
  dim(kmeans_input)
  
# Specify the directory (folder) to save the results.
  res_dir_cat_ave = "kmeans_Cat_ave" 
  
# Specify the prefix of filenames to be saved. 
  res_prefix_cat_ave = "VVKAJ_Cat_ave"
  
# Run elbow, silhouette, and gap methods to find an optimum K (number of clusters). 
  ChooseK(out.dir= res_dir_cat_ave, out.prefix= res_prefix_cat_ave)
  
# With specific K values in mind, perform k-means analysis with one specified K.
  OneK(myK= 4, out.dir= res_dir_cat_ave, out.fn = "VVKAJ_Cat_ave_K4")  
  oneKplot
  
# Try multiple Ks and print the biplots in one panel.
  MultipleK(myKs = c(2,3,4,6), out.dir = res_dir_cat_ave, out.fn = "VVKAJ_Cat_ave_K2-4&6")

  
# ---------------------------------------------------------------------------------------------------------------
# Come back to the main directory
  setwd(main_wd) 
  
  