# ===============================================================================================================
# Plot a food tree generated without using the FilterDBByDiet or Check.db functions.
# Version 1
# Created on 02/08/2023 by Rie Sadohara
# 06/26/2023 replaced "OTU" with "IFC".
# ===============================================================================================================

# Set your working directory as the main directory (dietary_patterns)
  Session --> Set working directory --> Choose directory.
  setwd("~/GitHub/DietR")

# Name your main directory for future use. 
  main_wd <- file.path(getwd())
  
# You can plot foodtrees you generated by using the ggtree package. 
# If you have not downloaded and installed the ggtree package yet: 
# You can do so by first installing BiocManager (if you have not done so):
  if (!require("BiocManager", quietly = TRUE))install.packages("BiocManager")
  
# Then, use BiocManager to install the "ggtree" package.
  # BiocManager::install("ggtree")
  
# The documentation for the ggtree package can be found in the developer's GitHub page 
# (https://guangchuangyu.github.io/software/ggtree/).
  

# Load the functions necessary to set directories.
  library(ggtree)
  source("lib/specify_data_dir.R")
  source("lib/viz_food_tree.r")
  
# You can come back to the main directory by:
  setwd(main_wd)
  
# ===============================================================================================================
  # Plot foodtrees
# ===============================================================================================================
# Go to the "Foodtree" directory where the tree files are saved. 
  SpecifyDataDirectory(directory.name = "eg_data/VVKAJ/Foodtree")
  
# Load the generated food tree. This will load the .nwk file and save it as a tree object called "tree".
# It is OK to see a message saying: 
# Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
# Also defined by 'tidytree'  
  tree <- read.tree("VVKAJ_Items_f_id_s_m_QCed_4Lv.tree.nwk")
  
# Prepare node labels of L1 for plotting. It assumes that the tree file has 9 L1 levels.
  PrepFoodTreePlots(input.tree=tree)
  
# Create a color-coded and annotated food tree with nine L1 levels.
  # It is OK to see some warning messages about Coordinate system and scale for 'y' already being present.
  VizFoodTree(input.tree=tree, layout="circular")
  
# Look at the color-coded and annotated food tree, saved as annotated_tree.
  annotated_tree
  
# Save the tree as a PDF file. 
  ggsave("VVKAJ_Items_f_id_s_m_QCed_4Lv.tree.pdf", 
         annotated_tree, device="pdf", width=6, height=6, units="in", dpi=300)
  
# You can also visualize trees of different levels; Lv2, Lv3, etc., which corresponds to the classification depth
# of each food item in the dataset. For example, Lv3 contains L1, L2, and L3 categories of food; whereas Lv4 
# contains L1, L2, L3, and L4 categories. Thus, as the level goes deeper, the more internal nodes there will 
# be in the food tree.
  
# ---------------------------------------------------------------------------------------------------------------
# Come back to the main directory.
  setwd(main_wd)  
  
  