# ===============================================================================================================
# Create a phyloseq object out of dietary and tree data and run ordination. Food tree level = 3
# Version 2
# Created on 02/06/2023 by Rie Sadohara
# 06/26/2023 replaced "OTU" with "IFC".
# ===============================================================================================================

# In this section, we will take the phylogeny of food items into account in clustering individuals according 
# to their dietary data. In order to do so, we will use the phyloseq package
# (https://joey711.github.io/phyloseq/index.html), which uses phylogeny of microbes and their abundance. 
# We will replace microbes with food items consumed by our dietary study participants.

# Set your working directory to the main directory.
  Session --> Set working directory --> Choose directory.
  setwd("~/GitHub/DietR")

# Name your main directory for future use. 
  main_wd <- file.path(getwd())

# ---------------------------------------------------------------------------------------------------------------
# Install the BiocManager package necessary for installing the phyloseq package. 
  if (!require("BiocManager",    quietly = TRUE))install.packages("BiocManager")
# Install the phyloseq package if you have not done so.
  # BiocManager::install("phyloseq")
  
# Install the devtools package necessary for installing the pairwiseAdonis package. 
  if (!require("devtools",    quietly = TRUE))install.packages("devtools")
# install pairwise adonis function from Github. (https://github.com/pmartinezarbizu/pairwiseAdonis)
  # devtools::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
  
# ---------------------------------------------------------------------------------------------------------------
# load the necessary packages and the source code.
  library(vegan)
  library(phyloseq)
  library(ggplot2)
  library(ggtree) # Shows how to cite the ggtree package. Make sure to cite it accordingly.
  library(SASxport)
  library(cluster) # necessary to the "pairwiseAdonis" package.
  library(pairwiseAdonis)
  source("lib/specify_data_dir.R")
  source("lib/ordination.R")
  source("lib/ggplot2themes.R")
  source("lib/sort_IFC_by_ID.R")
  source("lib/plot.axis.1to4.by.factor.R")

# Load the distinct 100 colors for use.   
  distinct100colors <- readRDS("lib/distinct100colors.rda")

# You can come back to the main directory by:
  setwd(main_wd)

# Set working directory.
  SpecifyDataDirectory("eg_data/NHANES/Laboratory_data/")

# ===============================================================================================================
# Create a phyloseq object for ordination. 
# ===============================================================================================================
  
# Load files for creating a phyloseq object.  

# Food 
# Load IFC table, and sort the columnnames (userID), leaving the last column (taxonomy) intact.
# This dataframe will be saved as "food".
# Also, save "food" as a .txt file to be used in the "correlation between Axes and foods" section.  
  SortIFCByID(ifc.input =           "Foodtree/Food_D12_FC_QC_demo_QCed_males60to79_3Lv.food.ifc.txt",
              outfn.for.corr.axis = "Foodtree/Food_D12_FC_QC_demo_QCed_males60to79_3Lv.food.ifc_sorted.txt")
  
  # "food" is a matrix of Food descriptions (rows) x SampleID (columns).
  # The column name of "food" is the ordered SEQNs preceded with an 'X'.
  head(food)[1:6, 1:4]

  # Format the food file and create an ifc_table called IFC.
  PrepFood(data = food)
 
# Taxonomy (tax)
  # Load taxonomy file generated by the MakeFoodTree function.   
  tax <- read.delim("Foodtree/Food_D12_FC_QC_demo_QCed_males60to79_3Lv.tax.txt")
  
  # Format the tax file and create a taxonomy table called TAX.
  PrepTax(data=tax)
  
# Sample
  # Load the demographics data.
  demog <- read.xport("../Raw_data/DEMO_I.XPT")  
  
  # Load our dataset that has the "GLU_index" information. 
  glu <- read.delim( file="QCtotal_d_ga_body_meta_glu_comp_2.txt", sep= "\t", header= T )
  
  # Take out only the SEQN and GLU_index.
  SEQN_GLU <- glu[, c("SEQN", "GLU_index")]
  
  # Add GLU_index to metadata. 
  demog_glu <- merge(x=SEQN_GLU, y=demog, all.x=T, by="SEQN")
  
  # Now, it has GLU_index.
  head(demog_glu, 2)
  
  # Add 'X' in front of the SEQN and define it as rownames.    
  rownames(demog_glu) <- paste("X", demog_glu$SEQN, sep="") 
  
  # Prep metadata for generating a phyloseq object.  
  PrepMeta_NHANES(data = demog_glu)
  
# Foodtree
  # Load foodtree file generated by the MakeFoodTree function.   
  foodtree <- read_tree("Foodtree/Food_D12_FC_QC_demo_QCed_males60to79_3Lv.nwk")
  # It is OK to see a message that says:
  # "Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
  # Also defined by 'tidytree'"
  
  # Format the food tree and save it as 'TREE'. 
  PrepTree(data=foodtree)
  # It is OK to see the same message as the previous line. 
  
# ---------------------------------------------------------------------------------------------------------------
# Create a phyloseq object with IFC, TAX, SAMPLES, and TREE.
  
  phyfoods <- phyloseq(IFC, TAX, SAMPLES, TREE)
  # It is OK to see the same message as the previous line. They may appear multiple times. 
  
# Check your metadata by using the functions in the phyloseq package.
# Show the sample names. Change n to adjust the number of rows to show.
  head(sample_names(phyfoods), n=6)  
  
# Show their metadata. 
  head(sample_data(phyfoods), n=4)
  
# Show only the columns (variables) of metadata. 
  sample_variables(phyfoods)
  
# Check the level 1 foods in your food tree 
  L1s <- tax_table(phyfoods)[, "L1"]
  as.vector(unique(L1s))

# Change to the folder called "Ordination" in your "Ordination" folder.
  SpecifyDataDirectory(directory.name = "eg_data/NHANES/Laboratory_data/Ordination/")

# ===============================================================================================================
# Perform ordination with WEIGHTED unifrac distance
# ===============================================================================================================
  
# Perform Principal Coordinate Analysis (PCoA) with WEIGHTED unifrac distance of your food data.
  # This may take a few minutes depending on your data size.
  # e.g. a large phyloseq object (7.9 MB) could take a few minutes.
  ordinated_w <- phyloseq::ordinate(phyfoods, method="PCoA", distance="unifrac", weighted=TRUE) 

# A warning message may appear saying:  
  # Warning message:
  #   In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  #               data length [xxxx] is not a sub-multiple or multiple of the number of rows [xxxx]
# This warns that the food tree we are using is not bifurcating. But it is OK, since we do not 
# expect our food trees to be bifurcating.
         
# Save the percent variance explained by the axes as a vector to use in plots.  
  eigen_percent_w <- ordinated_w$values$Relative_eig
  
# Save the percent variance explained as a txt file.
  Eigen(eigen.input = eigen_percent_w, 
        output.fn="Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_WEIGHTED_eigen.txt")

  
# ===============================================================================================================
# Plot your ordination results - WEIGHTED unifrac
# ===============================================================================================================
  
# Merge the first n axes to the metadata and save it as a txt file. 
# The merged dataframe, 'meta_usersdf', will be used for plotting.
  MergeAxesAndMetadata_NHANES(ord.object= ordinated_w, number.of.axes= 10, meta.data= demog_glu, 
                              output.fn= "Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_WEIGHTED_meta_users.txt")
  
# Load the output again for plotting.
  loaded_glu_w <- read.table("Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_WEIGHTED_meta_users.txt",
                             sep="\t", header=T)
  
# Convert the GLU_index as a factor to plot it in order.
  loaded_glu_w$GLU_index <- factor(loaded_glu_w$GLU_index, levels= c("Normal", "Prediabetic", "Diabetic"))
  table(loaded_glu_w$GLU_index)
  
# Load the eigenvalues as a vector.
  eigen_loaded <- read.table("Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_WEIGHTED_eigen.txt", header=T)

# Make a vector that contains the variance explained.
  eigen_loaded_vec <- eigen_loaded[, 2]
  
# ---------------------------------------------------------------------------------------------------------------
# Save Axes 1 & 2, 1 & 3, 2 & 3, 3 & 4, 2 & 4 biplots with and without ellipses with specified confidence interval.
# The reults are saved with filenames with the specified "prefix_AxisXY.pdf" or "prefix_AxisXY_ellipses.pdf".
# You need to supply the same number of colors in the order of the factor level to be used. 
# dot.colors are for datapoints, and ellipses.colors are for ellipses outlines. 
  PlotAxis1to4ByFactor(axis.meta.df    = loaded_glu_w, 
                       factor.to.color = "GLU_index", 
                       eigen.vector    = eigen_percent_w ,
                       dot.colors      = c("steelblue3", "yellow", "hotpink"), 
                       ellipses.colors = c("steelblue3", "gold3", "hotpink"),  
                       ellipses.cflevel = 0.95,
                       out.prefix = "Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_WEIGHTED")

# ---------------------------------------------------------------------------------------------------------------
# Permanova tests
  
# The GLU_index groups look different. Use beta-diversity and adonis tests to see
# if they are actually distinct from one another.

# Generate a weighted unifrac distance matrix.
  dist_matrix_w <- phyloseq::distance(phyfoods, method = "wunifrac") # weighted
  
# Perform dispersion test.
# vegan::betadisper computes centeroids and distance of each datapoint from it. 
  dispr_w <- vegan::betadisper(d=dist_matrix_w, phyloseq::sample_data(phyfoods)$GLU_index)

# Show the centroids and dispersion of each group. 
  plot(dispr_w)
 
# Use dispr to do a permutation test for homogeneity of multivariate dispersion.
# The set.seed function ensures the same permutation results will be obtained every time; 
# otherwise, the p-values will slightly differ each run,as it is a permutation test.
  set.seed(123)
  vegan::permutest(dispr_w, perm = 5000)
# If p>0.05, which is true in this case, the dispersion of each group are not different, and the assumption 
# for adonis is met.
  
# Use adonis to test whether there is a difference between groups' composition. 
  # i.e., composition among groups (food they consumed) is similar or not.
  set.seed(123)
  vegan::adonis(dist_matrix_w ~ phyloseq::sample_data(phyfoods)$GLU_index, permutations = 5000)

# The results indicate that the overall adonis is significant (p<0.05). If overall adonis is significant, 
# you can run pairwise adonis to see which group pairs are different.
  
# If overall adonis is significant, you can run pairwise adonis to see which group pairs are different.
  pairwise.adonis(dist_matrix_w, phyloseq::sample_data(phyfoods)$GLU_index, perm = 5000,
                  p.adjust.m = "none")  
  

# ===============================================================================================================
# Save weighted unifrac distance matrix
# ===============================================================================================================  

# Generate and save an WEIGHTED unifrac distance matrix of "Samples". 
  WeightedUnifracDis(input.phyloseq.obj = phyfoods, 
                     output.fn = "Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_WEIGHTED_uni_dis.txt")        
  
    
# ===============================================================================================================
# Use your phyloseq object and perform ordination - UNweighted
# ===============================================================================================================
  
# Perform Principal Coordinate Analysis (PCoA) with UNweighted unifrac distance of your food data.
# This may take a few minutes depending on your data size.
# e.g. a large phyloseq object (7.9 MB) takes ~ 1 min. 
  ordinated_u <- phyloseq::ordinate(phyfoods, method="PCoA", distance="unifrac", weighted=FALSE) 
  
# Save the percent variance explained by the axes as a vector to use in plots.  
  eigen_percent_u <- ordinated_u$values$Relative_eig
  
# Save the percent variance explained as a txt file.
  Eigen(eigen.input = eigen_percent_u, 
        output.fn="Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_UNweighted_eigen.txt")
  
# ===============================================================================================================
# Plot your ordination results - UNweighted
# ===============================================================================================================

# Merge the first n axes to the metadata and save it as a txt file. 
# The merged dataframe, 'meta_usersdf', will be used for plotting.
  MergeAxesAndMetadata_NHANES(ord.object= ordinated_u, number.of.axes= 10, meta.data= demog_glu, 
                              output.fn= "Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_UNweighted_meta_users.txt")
  
# Load the output again for plotting.
  loaded_glu_u <- read.table("Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_UNweighted_meta_users.txt",
                             sep="\t", header=T)  

# Convert the GLU_index as a factor to plot it in order.
  loaded_glu_u$GLU_index <- factor(loaded_glu_u$GLU_index, levels = c("Normal", "Prediabetic", "Diabetic"))

# Take a look at meta_usersdf_loaded. 
  head(loaded_glu_u, 2)
  
# ---------------------------------------------------------------------------------------------------------------
# Save Axes 1 & 2, 1 & 3, 2 & 3, 3 & 4, 2 & 4 biplots with and without ellipses with specified confidence interval.
# The reults are saved with filenames with the specified "prefix_AxisXY.pdf" or "prefix_AxisXY_ellipses.pdf".
# You need to supply the same number of colors in the order of the factor level to be used. 
# dot.colors are for datapoints, and ellipses.colors are for ellipses outlines. 
# [NOTE] For the "UNweighted" results, change the input, eigen vectors, and prefix names accordingly. 
  PlotAxis1to4ByFactor(axis.meta.df    = loaded_glu_u, 
                       factor.to.color = "GLU_index", 
                       eigen.vector    = eigen_percent_u ,
                       dot.colors      = c("steelblue3", "yellow", "hotpink"), 
                       ellipses.colors = c("steelblue3", "gold3", "hotpink"),  
                       ellipses.cflevel = 0.95,
                       out.prefix = "Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_UNweighted")

# ---------------------------------------------------------------------------------------------------------------
# Permanova tests
  
# It is not clear from the plots whether The GLU_index groups are different. Use beta-diversity and adonis 
# tests to see if they are they actually distinct from one another.

# Generate an UNweighted unifrac distance matrix.
  dist_matrix_u <- phyloseq::distance(phyfoods, method="unifrac")  # UNweighted
  
# Perform dispersion test.
  # vegan::betadisper computes centeroids and distance of each datapoint from it. 
  dispr_u <- vegan::betadisper(dist_matrix_u, phyloseq::sample_data(phyfoods)$GLU_index)
  
# Can show the centroids and dispersion of each group. 
  plot(dispr_u)
  
# Use dispr to do a permutation test for homogeneity of multivariate dispersion.
  set.seed(123)
  vegan::permutest(dispr_u, perm = 5000)
  # If p>0.05, the dispersion of each group are not different, and the assumption for adonis is met.
  
# Use adonis to test whether there is a difference between groups' composition. 
  # i.e., composition among groups (food they consumed) is similar or not.
  set.seed(123)
  vegan::adonis(dist_matrix_u ~ phyloseq::sample_data(phyfoods)$GLU_index, permutations = 5000) 
  
# If overall adonis is significant, which is not true in this case, but we will run pairwise adonis 
# for demonstration purposes.
  pairwise.adonis(dist_matrix_u, phyloseq::sample_data(phyfoods)$GLU_index, perm = 5000,
                  p.adjust.m = "none")
  
# ===============================================================================================================
# Save unifrac distance (UNweighted or WEIGHTED) matrices 
# ===============================================================================================================

# Generate and save an UNweighted unifrac distance matrix of "Samples". 
  UnweightedUnifracDis(input.phyloseq.obj = phyfoods, 
                       output.fn = "Food_D12_FC_QC_demo_QCed_males60to79_3Lv_ord_UNweighted_uni_dis.txt")        

# ---------------------------------------------------------------------------------------------------------------
# Come back to the main directory.
  setwd(main_wd)  
  
